Repository roscisz/TensorHive, pull requests merged in 2018-10, with the labels that each got.

#88 Feature/users
  authorization.py
  tensorhive/api/APIServer.py
  tensorhive/api/api_specification.yml
  tensorhive/api/controllers/user.py
  tensorhive/api/controllers/users.py
  tensorhive/authorization.py
  tensorhive/cli.py
  tensorhive/controllers/reservation_event/DestroyEventController.py
  tensorhive/controllers/user/CreateUserController.py
  tensorhive/controllers/user/DeleteUserController.py
  tensorhive/controllers/user/UserLoginController.py
  tensorhive/controllers/user/UserLogoutController.py
  tensorhive/database.py
  tensorhive/models/auth/RevokedTokenModel.py
  tensorhive/models/role/RoleModel.py
  tensorhive/models/role/__init__.py
  tensorhive/models/user/UserModel.py
Labels: enhancement

#93 Inject custom logger to API server (gevent backend)
  tensorhive/api/APIServer.py
Labels: enhancement

#94 Introduce colored output utility.
  tensorhive/api/APIServer.py
  tensorhive/app/web/AppServer.py
  tensorhive/cli.py
  tensorhive/core/utils/colors.py
Labels: enhancement

#104 Allow reservations to be like: A.ends_at == B.starts_at
  tensorhive/models/Reservation.py
Labels: waiting-for-review

#103 Disable connexion requests validator (let backend handle this)
  tensorhive/api/api_specification.yml
Labels: waiting-for-review

#105 Inject API URL into `config.json` dynamically at `tensorhive` startup.
  tensorhive/app/web/AppServer.py
Labels: enhancement, waiting-for-review

#102 Set of web application patches for 0.2 release
  tensorhive/app/web/dev/src/components/TheCreate.vue
  tensorhive/app/web/dev/src/components/TheDash.vue
  tensorhive/app/web/dev/src/components/TheLogin.vue
  tensorhive/app/web/dev/src/components/views/ReservationsOverview.vue
  tensorhive/app/web/dev/src/components/views/UsersOverview.vue
  tensorhive/app/web/dev/src/components/views/nodes_overview/WatchBox.vue
  tensorhive/app/web/dev/src/components/views/nodes_overview/WatchGenerator.vue
  tensorhive/app/web/dev/src/components/views/reserve_resources/FullCalendar.vue
  tensorhive/app/web/dev/src/components/views/reserve_resources/FullCalendarReserve.vue
  tensorhive/app/web/dev/src/main.js
  tensorhive/app/web/dev/src/store/mutations.js
  tensorhive/app/web/dev/src/store/state.js
  tensorhive/app/web/dev/static/config.json
  tensorhive/app/web/dev/static/config/index.js
Labels: enhancement
